// Generated by CoffeeScript 1.3.3
(function() {
  var Test, a, b, c,
    _this = this;

  a = function(x, y) {
    return x * x + y;
  };

  Test = (function() {

    function Test(a) {
      this.a = a;
    }

    return Test;

  })();

  b = 3;

  if ((b != null) && (typeof d !== "undefined" && d !== null)) {
    c = a(3);
  }

}).call(this);
